/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as BlogChessbaseFreeAlternativeIndexRouteImport } from './routes/blog/chessbase-free-alternative/index'
import { Route as DocsFaqIndexRouteImport } from './routes/docs/faq/index'
import { Route as DocsFirstStepsIndexRouteImport } from './routes/docs/first-steps/index'
import { Route as DocsInstallationIndexRouteImport } from './routes/docs/installation/index'
import { Route as FeaturesDatabaseIndexRouteImport } from './routes/features/database/index'
import { Route as FeaturesRepertoireTrainingIndexRouteImport } from './routes/features/repertoire-training/index'
import { Route as FeaturesSmartAnalysisIndexRouteImport } from './routes/features/smart-analysis/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogChessbaseFreeAlternativeIndexRoute =
  BlogChessbaseFreeAlternativeIndexRouteImport.update({
    id: '/blog/chessbase-free-alternative/',
    path: '/blog/chessbase-free-alternative/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsFaqIndexRoute = DocsFaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFirstStepsIndexRoute = DocsFirstStepsIndexRouteImport.update({
  id: '/first-steps/',
  path: '/first-steps/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationIndexRoute = DocsInstallationIndexRouteImport.update({
  id: '/installation/',
  path: '/installation/',
  getParentRoute: () => DocsRoute,
} as any)
const FeaturesDatabaseIndexRoute = FeaturesDatabaseIndexRouteImport.update({
  id: '/features/database/',
  path: '/features/database/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRepertoireTrainingIndexRoute =
  FeaturesRepertoireTrainingIndexRouteImport.update({
    id: '/features/repertoire-training/',
    path: '/features/repertoire-training/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesSmartAnalysisIndexRoute =
  FeaturesSmartAnalysisIndexRouteImport.update({
    id: '/features/smart-analysis/',
    path: '/features/smart-analysis/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/llms/txt': typeof LlmsTxtRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/blog/chessbase-free-alternative/': typeof BlogChessbaseFreeAlternativeIndexRoute
  '/docs/faq/': typeof DocsFaqIndexRoute
  '/docs/first-steps/': typeof DocsFirstStepsIndexRoute
  '/docs/installation/': typeof DocsInstallationIndexRoute
  '/features/database/': typeof FeaturesDatabaseIndexRoute
  '/features/repertoire-training/': typeof FeaturesRepertoireTrainingIndexRoute
  '/features/smart-analysis/': typeof FeaturesSmartAnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/blog/chessbase-free-alternative': typeof BlogChessbaseFreeAlternativeIndexRoute
  '/docs/faq': typeof DocsFaqIndexRoute
  '/docs/first-steps': typeof DocsFirstStepsIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/features/database': typeof FeaturesDatabaseIndexRoute
  '/features/repertoire-training': typeof FeaturesRepertoireTrainingIndexRoute
  '/features/smart-analysis': typeof FeaturesSmartAnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/llms/txt': typeof LlmsTxtRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/blog/chessbase-free-alternative/': typeof BlogChessbaseFreeAlternativeIndexRoute
  '/docs/faq/': typeof DocsFaqIndexRoute
  '/docs/first-steps/': typeof DocsFirstStepsIndexRoute
  '/docs/installation/': typeof DocsInstallationIndexRoute
  '/features/database/': typeof FeaturesDatabaseIndexRoute
  '/features/repertoire-training/': typeof FeaturesRepertoireTrainingIndexRoute
  '/features/smart-analysis/': typeof FeaturesSmartAnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/llms/txt'
    | '/blog/'
    | '/docs/'
    | '/features/'
    | '/blog/chessbase-free-alternative/'
    | '/docs/faq/'
    | '/docs/first-steps/'
    | '/docs/installation/'
    | '/features/database/'
    | '/features/repertoire-training/'
    | '/features/smart-analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms/txt'
    | '/blog'
    | '/docs'
    | '/features'
    | '/blog/chessbase-free-alternative'
    | '/docs/faq'
    | '/docs/first-steps'
    | '/docs/installation'
    | '/features/database'
    | '/features/repertoire-training'
    | '/features/smart-analysis'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/llms/txt'
    | '/blog/'
    | '/docs/'
    | '/features/'
    | '/blog/chessbase-free-alternative/'
    | '/docs/faq/'
    | '/docs/first-steps/'
    | '/docs/installation/'
    | '/features/database/'
    | '/features/repertoire-training/'
    | '/features/smart-analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  LlmsTxtRoute: typeof LlmsTxtRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  BlogChessbaseFreeAlternativeIndexRoute: typeof BlogChessbaseFreeAlternativeIndexRoute
  FeaturesDatabaseIndexRoute: typeof FeaturesDatabaseIndexRoute
  FeaturesRepertoireTrainingIndexRoute: typeof FeaturesRepertoireTrainingIndexRoute
  FeaturesSmartAnalysisIndexRoute: typeof FeaturesSmartAnalysisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/chessbase-free-alternative/': {
      id: '/blog/chessbase-free-alternative/'
      path: '/blog/chessbase-free-alternative'
      fullPath: '/blog/chessbase-free-alternative/'
      preLoaderRoute: typeof BlogChessbaseFreeAlternativeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq/': {
      id: '/docs/faq/'
      path: '/faq'
      fullPath: '/docs/faq/'
      preLoaderRoute: typeof DocsFaqIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/first-steps/': {
      id: '/docs/first-steps/'
      path: '/first-steps'
      fullPath: '/docs/first-steps/'
      preLoaderRoute: typeof DocsFirstStepsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation/': {
      id: '/docs/installation/'
      path: '/installation'
      fullPath: '/docs/installation/'
      preLoaderRoute: typeof DocsInstallationIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/features/database/': {
      id: '/features/database/'
      path: '/features/database'
      fullPath: '/features/database/'
      preLoaderRoute: typeof FeaturesDatabaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/repertoire-training/': {
      id: '/features/repertoire-training/'
      path: '/features/repertoire-training'
      fullPath: '/features/repertoire-training/'
      preLoaderRoute: typeof FeaturesRepertoireTrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/smart-analysis/': {
      id: '/features/smart-analysis/'
      path: '/features/smart-analysis'
      fullPath: '/features/smart-analysis/'
      preLoaderRoute: typeof FeaturesSmartAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsFaqIndexRoute: typeof DocsFaqIndexRoute
  DocsFirstStepsIndexRoute: typeof DocsFirstStepsIndexRoute
  DocsInstallationIndexRoute: typeof DocsInstallationIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsFaqIndexRoute: DocsFaqIndexRoute,
  DocsFirstStepsIndexRoute: DocsFirstStepsIndexRoute,
  DocsInstallationIndexRoute: DocsInstallationIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  LlmsTxtRoute: LlmsTxtRoute,
  BlogIndexRoute: BlogIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  BlogChessbaseFreeAlternativeIndexRoute:
    BlogChessbaseFreeAlternativeIndexRoute,
  FeaturesDatabaseIndexRoute: FeaturesDatabaseIndexRoute,
  FeaturesRepertoireTrainingIndexRoute: FeaturesRepertoireTrainingIndexRoute,
  FeaturesSmartAnalysisIndexRoute: FeaturesSmartAnalysisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
